"""empty message

Revision ID: b9c5a5b55322
Revises: 3c799de12800
Create Date: 2021-06-05 09:53:35.034441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9c5a5b55322'
down_revision = '3c799de12800'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('test', sa.VARCHAR(length=150), nullable=True))
    # ### end Alembic commands ###
